modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="modum"
version="1.0.0"
displayName="ModUm"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="RoLoTech, MCreator"

[[dependencies.modum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



